version: "3.8"

services:
  algodaily-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - 5173:5173
    environment:
      - VITE_BACKEND_BASE_URL=$VITE_BACKEND_BASE_URL
    networks:
      - algodaily-network

networks:
  algodaily-network:
    external: true
